import os

OLLAMA_EMBED_MODEL = os.getenv("OLLAMA_EMBED_MODEL")
OLLAMA_EMBED_MODEL = os.getenv("OLLAMA_EMBED_MODEL")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL")
OLLAMA_URL   = os.getenv("OLLAMA_HOST")
CHROMA_HOST = os.getenv("CHROMA_SERVER_HOST")
CHROMA_PORT = int(os.getenv("CHROMA_SERVER_PORT"))
