services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    gpus: all
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    environment:
      - OLLAMA_MODEL
      - OLLAMA_EMBED_MODEL

  f5tts:
    build:
      context: ./submodules/F5-TTS
      dockerfile: Dockerfile
    image: f5tts:v1
    container_name: f5tts
    gpus: all
    volumes:
      - f5-tts:/root/.cache/huggingface/hub/
    ports:
      - "7860:7860"
    command:
      - "f5-tts_infer-gradio"
      - "--host"
      - "0.0.0.0"
    depends_on:
      - ollama
    restart: unless-stopped

  chromadb:
    image: chromadb/chroma:0.6.3
    container_name: chromadb
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=TRUE
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console UI
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    command: server /data --console-address ":9001"
    restart: unless-stopped

  fastapi:
    build:
      context: ./rest-api
      dockerfile: Dockerfile
    image: my-fastapi:latest
    container_name: fastapi
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL
      - OLLAMA_EMBED_MODEL
      - CHROMA_SERVER_HOST=chromadb
      - CHROMA_SERVER_PORT=8000
      - TTS_HOST=f5tts
      - TTS_PORT=7860
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
      - MINIO_HOST=minio:9000
    ports:
      - "8000:80"
    depends_on:
      - ollama
      - f5tts
      - chromadb
      - minio
    restart: unless-stopped

volumes:
  ollama:
  f5-tts:
  chroma_data:
  minio_data: