version: "3.8"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    gpus: all
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

  f5tts:
    build:
      context: ./submodules/F5-TTS
      dockerfile: Dockerfile
    image: f5tts:v1
    container_name: f5tts
    gpus: all
    volumes:
      - f5-tts:/root/.cache/huggingface/hub/
    ports:
      - "7860:7860"
    command:
      - "f5-tts_infer-gradio"
      - "--host"
      - "0.0.0.0"
    depends_on:
      - ollama
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped

volumes:
  ollama:
  f5-tts:
  qdrant_storage: